### ISSUE TITLE
d.ts声明的全局对象无效

### ISSUE THREAD

**Issue by 0fan** [LZHD/vue-vite-h5#1]
![image](https://user-images.githubusercontent.com/10867096/159116887-addd40a7-f083-4928-ae39-5fb5d899f318.png)
![image](https://user-images.githubusercontent.com/10867096/159116898-f0280b2d-40bb-4f3a-951c-daba7c0795a7.png)
![image](https://user-images.githubusercontent.com/10867096/159116910-038e14a3-d274-4653-a9bb-1d5db8fe1509.png)

**Comment by 202780181** [comment]
> ![image](https://user-images.githubusercontent.com/10867096/159116887-addd40a7-f083-4928-ae39-5fb5d899f318.png) ![image](https://user-images.githubusercontent.com/10867096/159116898-f0280b2d-40bb-4f3a-951c-daba7c0795a7.png) ![image](https://user-images.githubusercontent.com/10867096/159116910-038e14a3-d274-4653-a9bb-1d5db8fe1509.png)

全局.d.ts 请放在src目录下 (typings 已成局部了)

**Comment by 202780181** [comment]
> ![image](https://user-images.githubusercontent.com/10867096/159116887-addd40a7-f083-4928-ae39-5fb5d899f318.png) ![image](https://user-images.githubusercontent.com/10867096/159116898-f0280b2d-40bb-4f3a-951c-daba7c0795a7.png) ![image](https://user-images.githubusercontent.com/10867096/159116910-038e14a3-d274-4653-a9bb-1d5db8fe1509.png)


在申明文件最后添加导出空对象

**Comment by 202780181** [comment]
> ![image](https://user-images.githubusercontent.com/10867096/159116887-addd40a7-f083-4928-ae39-5fb5d899f318.png) ![image](https://user-images.githubusercontent.com/10867096/159116898-f0280b2d-40bb-4f3a-951c-daba7c0795a7.png) ![image](https://user-images.githubusercontent.com/10867096/159116910-038e14a3-d274-4653-a9bb-1d5db8fe1509.png)



在申明文件尾部添加导出空对象
像这样:


declare global {
  // **** declare
	declare type IS_Pro = string;
}

export {}
